### ISSUE TITLE
Automatically fetch calendar info to update meetup date above main fold

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/codeforhawaii.github.io#19]
The website is out of date as it lists June 24th (a week ago) as the next meetup at the bottom of the front page.

I _could_ make the change manually, but have a few points to bring up before doing so:
- Do we list the online Google Hangouts meetup, or only the physical meetup at BoxJelly?
  - If both, do we only show the upcoming or maybe both concurrently?
- Could this be easily automated to always update to the upcoming second Monday of the month and last Wednesday, respectively?
- **Or** is it just best to manually update it?  If so, someone needs to be tasked with consistently updating it every two weeks.

**Comment by rbvea** [comment]
Since it's a regular occurrence, I'd think it'd be best for the events to be regularly automated.  We should also include the hangouts link.

**Comment by ryankanno** [comment]
To answer your q's:
- I think listing both would be ideal.
- I'd suggest not making that change (since the venue may change) and just reading it off the calendar like HI Capacity does. It should be trivial to get the json calendar data.
- In lieu of having 2, we need to manually update it. I wouldn't worry too much about it though, since I know 2 is pretty easily done (and we don't have a ton of traffic yet) - so it's not going to move any needles.

**Comment by ryankanno** [comment]
I'll leave this here as reference: http://stackoverflow.com/questions/28262674/retrieve-google-calendar-events-using-api-v3-in-javascript

**Comment by mckaydavis** [comment]
I've updated the HTML to include both July 2015 meetups in e74f7badda1451f2e800e647845a538f27169445.

We can revisit automating the updates if manual is not maintained well.

**Comment by ryankanno** [comment]
I was just going to cut and paste that snippet today at devops club. :D

**Comment by ryankanno** [comment]
Checked in 0fee4a43f0706cf99756beec40f290917ad84bf8
